//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabTsak_product_.Models.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Addtocart
    {
        public int A_id { get; set; }
        public int order_id { get; set; }
        public string p_name { get; set; }
        public string p_qty { get; set; }
        public string p_price { get; set; }
    }
}
