//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabTsak_product_.Models.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class myorder
    {
        public int Order_id { get; set; }
        public System.DateTime order_time { get; set; }
        public string total_order { get; set; }
    }
}
